_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.12
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
accum_iter:
    value: 1
attribute:
    value: race
batch_size:
    value: 32
batchsize_fairloss:
    value: 32
dataset_dir:
    value: ../data/Harvard-FairVLMed
eval_set:
    value: test
lambda_fairloss:
    value: 0.001
lr:
    value: 1e-05
model_arch:
    value: vit-l14
momentum:
    value: 0.9
num_epochs:
    value: 10
perf_file:
    value: vit-l14_slo_fundus_1e-3FairerCLIP_differentsinkhorn.csv
pretrained_weights:
    value: ""
project:
    value: rewroteOGcodeV2beforedeadline
result_dir:
    value: ../results//run_anew/rewrite_their_code/FairerCLIP/glaucoma_FairerCLIP_vit-l14_32_1e-3_1e-5
seed:
    value: 5613
sinkhorn_blur:
    value: 0.0001
sinkhorn_diameter:
    value: null
sinkhorn_scaling:
    value: 0.9
summarized_note_file:
    value: gpt-4_summarized_notes.csv
text_source:
    value: note
weight_decay:
    value: 6e-05
weightslist:
    value:
        - 0.5
        - 0.5
        - 0
        - 0
workers:
    value: 4
